name: Cilium Conformance E2E (ci-e2e-1.13)
'on':
  issue_comment:
    types:
    - created
  schedule:
  - cron: 0 10 * * *
permissions:
  contents: read
  pull-requests: read
  statuses: write
concurrency:
  group: "${{ github.workflow }}\n${{ github.event_name }}\n${{\n  (github.event_name\
    \ == 'schedule' && github.sha) ||\n  (github.event_name == 'issue_comment' &&\
    \ (\n    github.event.comment.body == '/ci-e2e-1.13' ||\n    github.event.comment.body\
    \ == '/test-backport-1.13'\n  ) && github.event.issue.number) ||\n  (github.event_name\
    \ == 'pull_request' && github.event.pull_request.number)\n}}\n"
  cancel-in-progress: true
env:
  cilium_cli_version: v0.14.2
  cilium_cli_ci_version: null
  check_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id
    }}
jobs:
  check_changes:
    name: Deduce required tests from code changes
    if: "(github.event_name == 'issue_comment' && (\n  github.event.comment.body ==\
      \ '/ci-e2e-1.13' ||\n  github.event.comment.body == '/test-backport-1.13'\n\
      )) ||\ngithub.event_name == 'schedule' ||\ngithub.event_name == 'pull_request'\n"
    runs-on: ubuntu-latest
    outputs:
      tested: ${{ steps.tested-tree.outputs.src }}
    steps:
    - name: Checkout code
      if: ${{ github.event.issue.pull_request }}
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      with:
        persist-credentials: false
    - name: Retrieve pull request's base and head
      if: ${{ github.event.issue.pull_request }}
      id: pr
      run: 'curl ${{ github.event.issue.pull_request.url }} > pr.json

        echo "base=$(jq -r ''.base.sha'' pr.json)" >> $GITHUB_OUTPUT

        echo "head=$(jq -r ''.head.sha'' pr.json)" >> $GITHUB_OUTPUT

        '
    - name: Check code changes
      if: ${{ github.event.issue.pull_request }}
      uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
      id: tested-tree
      with:
        base: ${{ steps.pr.outputs.base }}
        ref: ${{ steps.pr.outputs.head }}
        filters: "src:\n  - '!(test|Documentation)/**'\n"
  setup-report:
    runs-on: ubuntu-latest
    needs: check_changes
    name: Set commit status
    outputs:
      sha: ${{ steps.vars.outputs.sha }}
    steps:
    - name: Set up job variables
      id: vars
      run: "if [ ${{ github.event.issue.pull_request || github.event.pull_request\
        \ }} ]; then\n  PR_API_JSON=$(curl \\\n    -H \"Accept: application/vnd.github.v3+json\"\
        \ \\\n    -H \"Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}\" \\\n  \
        \  ${{ github.event.issue.pull_request.url || github.event.pull_request.url\
        \ }})\n  SHA=$(echo \"$PR_API_JSON\" | jq -r \".head.sha\")\nelif [ \"${{\
        \ github.event_name }}\" = \"schedule\" ]; then\n  curl https://api.github.com/repos/cilium/cilium/branches/v1.13\
        \ > branch.json\n  SHA=$(jq -r '.commit.sha' branch.json)\nelse\n  SHA=${{\
        \ github.sha }}\nfi\necho \"sha=${SHA}\" >> $GITHUB_OUTPUT\n"
    - name: Set commit status to pending
      uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.vars.outputs.sha }}
        context: ${{ github.workflow }}
        description: E2E conformance tests in progress...
        state: pending
        target_url: ${{ env.check_url }}
  skip-test-run:
    if: github.event.comment.body == '/test' && needs.check_changes.outputs.tested
      == 'false'
    runs-on: ubuntu-latest
    needs: setup-report
    name: Set commit status to success (skipped)
    steps:
    - name: Set commit status to success
      uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ needs.setup-report.outputs.sha }}
        context: ${{ github.workflow }}
        description: E2E conformance tests skipped
        state: success
        target_url: ${{ env.check_url }}
  setup-and-test:
    runs-on: ubuntu-latest
    needs: setup-report
    name: Setup & Test
    if: "(github.event_name == 'issue_comment' && (\n  github.event.comment.body ==\
      \ '/ci-e2e-1.13' ||\n  (github.event.comment.body == '/test-backport-1.13' &&\
      \ needs.check_changes.outputs.tested == 'true')\n)) ||\ngithub.event_name ==\
      \ 'schedule' ||\ngithub.event_name == 'pull_request'\n"
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: '1'
          kernel: 4.19-main
          kube-proxy: iptables
          kpr: disabled
          tunnel: vxlan
          encryption: ipsec
          ipv6: 'false'
        - name: '2'
          kernel: 5.4-main
          kube-proxy: iptables
          kpr: disabled
          tunnel: disabled
          encryption: ipsec
        - name: '3'
          kernel: 5.10-main
          kube-proxy: iptables
          kpr: disabled
          tunnel: disabled
          encryption: ipsec
          endpoint-routes: 'true'
        - name: '4'
          kernel: 5.10-main
          kube-proxy: iptables
          kpr: strict
          tunnel: vxlan
          encryption: disabled
          lb-mode: snat
          endpoint-routes: 'true'
        - name: '5'
          kernel: 5.15-main
          kube-proxy: iptables
          kpr: strict
          tunnel: disabled
          encryption: disabled
          lb-mode: snat
          endpoint-routes: 'true'
        - name: '6'
          kernel: 6.0-main
          kube-proxy: none
          kpr: strict
          tunnel: vxlan
          encryption: disabled
          lb-mode: snat
        - name: '7'
          kernel: bpf-next-main
          kube-proxy: none
          kpr: strict
          tunnel: disabled
          encryption: disabled
          lb-mode: snat
        - name: '8'
          kernel: bpf-next-main
          kube-proxy: iptables
          kpr: disabled
          tunnel: vxlan
          encryption: ipsec
          endpoint-routes: 'true'
    timeout-minutes: 60
    steps:
    - name: Checkout main branch to access local actions
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      with:
        ref: ${{ github.event.repository.default_branch }}
        persist-credentials: false
    - name: Set Environment Variables
      uses: ./.github/actions/set-env-variables
    - name: Set up job variables
      id: vars
      run: "SHA=\"${{ needs.setup-report.outputs.sha }}\"\nCILIUM_INSTALL_DEFAULTS=\"\
        --wait \\\n  --chart-directory=./install/kubernetes/cilium \\\n  --helm-set=image.repository=quay.io/${{\
        \ env.QUAY_ORGANIZATION_DEV }}/cilium-ci \\\n  --helm-set=image.useDigest=false\
        \ \\\n  --helm-set=image.tag=${SHA} \\\n  --helm-set=operator.image.repository=quay.io/${{\
        \ env.QUAY_ORGANIZATION_DEV }}/operator \\\n  --helm-set=operator.image.suffix=-ci\
        \ \\\n  --helm-set=operator.image.tag=${SHA} \\\n  --helm-set=operator.image.useDigest=false\
        \ \\\n  --helm-set=hubble.relay.image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV\
        \ }}/hubble-relay-ci \\\n  --helm-set=hubble.relay.image.tag=${SHA} \\\n \
        \ --rollback=false \\\n  --config monitor-aggregation=none \\\n  --nodes-without-cilium=kind-worker3\
        \ \\\n  --helm-set-string=kubeProxyReplacement=${{ matrix.kpr }} \\\n  --helm-set=bpf.masquerade=false\"\
        \nTUNNEL=\"--helm-set-string=tunnel=vxlan\"\nif [ \"${{ matrix.tunnel }}\"\
        \ == \"disabled\" ]; then\n  TUNNEL=\"--helm-set-string=tunnel=disabled --helm-set-string=autoDirectNodeRoutes=true\
        \ --helm-set-string=ipv4NativeRoutingCIDR=10.244.0.0/16\"\n  TUNNEL=\"${TUNNEL}\
        \ --helm-set-string=ipv6NativeRoutingCIDR=fd00:10:244::/56\"\nfi\nLB_MODE=\"\
        \"\nif [ \"${{ matrix.lb-mode }}\" != \"\" ]; then\n  LB_MODE=\"--helm-set-string=loadBalancer.mode=${{\
        \ matrix.lb-mode }}\"\nfi\nENDPOINT_ROUTES=\"\"\nif [ \"${{ matrix.endpoint-routes\
        \ }}\" == \"true\" ]; then\n  ENDPOINT_ROUTES=\"--helm-set-string=endpointRoutes.enabled=true\"\
        \nfi\nIPV6=\"\"\nif [ \"${{ matrix.ipv6 }}\" != \"false\" ]; then\n  IPV6=\"\
        --helm-set=ipv6.enabled=true\"\nfi\n\nCONFIG=\"${CILIUM_INSTALL_DEFAULTS}\
        \ ${TUNNEL} ${LB_MODE} ${ENDPOINT_ROUTES} ${IPV6}\"\necho \"cilium_install_defaults=${CONFIG}\"\
        \ >> $GITHUB_OUTPUT\n"
    - name: Checkout pull request for Helm chart
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      with:
        ref: ${{ needs.setup-report.outputs.sha }}
        persist-credentials: false
    - name: Install Cilium CLI-cli
      uses: cilium/cilium-cli@b5af8b2ce225699954dd5204e6e65e500711973e
      with:
        release-version: ${{ env.cilium_cli_version }}
        ci-version: ${{ env.cilium_cli_ci_version }}
        binary-name: cilium-cli
        binary-dir: ./
    - name: Provision LVH VMs
      uses: cilium/little-vm-helper@0b7d7157dae56a44dc531c852e7756dc671071af
      with:
        test-name: e2e-conformance
        image-version: ${{ matrix.kernel }}
        host-mount: ./
        cpu: 4
        dns-resolver: 1.1.1.1
        install-dependencies: 'true'
        cmd: 'git config --global --add safe.directory /host

          '
    - name: Wait for images to be available
      timeout-minutes: 10
      shell: bash
      run: "for image in cilium-ci operator-generic-ci hubble-relay-ci ; do\n  until\
        \ docker manifest inspect quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/$image:${{\
        \ needs.setup-report.outputs.sha }} &> /dev/null; do sleep 45s; done\ndone\n"
    - name: Run kube-proxy tests
      uses: cilium/little-vm-helper@0b7d7157dae56a44dc531c852e7756dc671071af
      with:
        provision: 'false'
        cmd: "cd /host/\n./contrib/scripts/kind.sh \"\" 3 \"\" \"\" \"${{ matrix.kube-proxy\
          \ }}\" \"dual\"\n./cilium-cli install ${{ steps.vars.outputs.cilium_install_defaults\
          \ }}\n\n# install static routes\nEXTERNAL_FROM_CIDRS=(\\$(kubectl get nodes\
          \ -o jsonpath='{range .items[*]}{.spec.podCIDR}{\"\\n\"}{end}'))\nEXTERNAL_NODE_IPS=()\
          \ # Nodes IPs are collected to be passed to the Cilium CLI later on.\nNODES_WITHOUT_CILIUM=kind-worker3\
          \ # To add more elements, keep it comma-separated.\n\n# Loop over each pod\
          \ CIDR from all nodes.\nfor i in \"\\${!EXTERNAL_FROM_CIDRS[@]}\"; do\n\
          \  EXTERNAL_FROM_CIDR=\\${EXTERNAL_FROM_CIDRS[i]}\n\n  if [[ \\$EXTERNAL_FROM_CIDR\
          \ =~ ^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+/[0-9]+$ ]]; then\n    IP_FAMILY=\"\
          v4\"\n  elif [[ \\$EXTERNAL_FROM_CIDR =~ ^[0-9a-fA-F:]+/[0-9]+$ ]]; then\n\
          \    IP_FAMILY=\"v6\"\n  else\n    echo \"ERROR: Malformed pod CIDR '\\\
          ${EXTERNAL_FROM_CIDR}'\" >&2\n    exit 1\n  fi\n\n  IFS=',' read -ra NODES_WITHOUT\
          \ <<< \"\\$NODES_WITHOUT_CILIUM\" # Split by comma into an array\n  for\
          \ WITHOUT in \"\\${NODES_WITHOUT[@]}\"; do\n    # Fetch node with a specific\
          \ pod CIDR.\n    node=\\$(kubectl get nodes -o jsonpath=\"{range .items[?(@.spec.podCIDR\
          \ == '\\$EXTERNAL_FROM_CIDR')]}{@.metadata.name}{end}\")\n    if [[ -z \"\
          \\$node\" ]]; then\n      echo \"ERROR: Could not find node with .spec.podCIDR\
          \ matching \\${EXTERNAL_FROM_CIDR}\" >&2\n      exit 1\n    fi\n    for\
          \ NODE_IP in \\$(kubectl get node \"\\$node\" -o jsonpath=\"{.status.addresses[?(@.type\
          \ == 'InternalIP')].address}\"); do\n      # Skip if the node IP's family\
          \ mismatches with pod CIDR's\n      # family. Cannot create a route with\
          \ the gateway IP family\n      # mismatching the subnet.\n      if [[ \"\
          \\$IP_FAMILY\" == \"v4\" && ! \"\\$NODE_IP\" =~ \\. ]]; then\n        continue\n\
          \      elif [[ \"\\$IP_FAMILY\" == \"v6\" && ! \"\\$NODE_IP\" =~ \\: ]];\
          \ then\n        continue\n      fi\n      # Install static route on the\
          \ host, towards the pod CIDR via the node IP.\n      docker exec \"\\$WITHOUT\"\
          \ ip route replace \"\\${EXTERNAL_FROM_CIDR}\" via \"\\${NODE_IP}\"\n  \
          \    EXTERNAL_NODE_IPS+=(\"\\${NODE_IP}\")\n    done\n  done\ndone\n\n#\
          \ Join the elements with a comma delimiter, or leave them unmodified\n#\
          \ if there's only one element so that it can be passed properly to\n# the\
          \ CLI.\nif [[ \\${#EXTERNAL_NODE_IPS[@]} -eq 1 ]]; then\n  EXTERNAL_NODE_IPS_PARAM=\"\
          \\${EXTERNAL_NODE_IPS[0]}\"\nelse\n  EXTERNAL_NODE_IPS_PARAM=\\$(IFS=',';\
          \ echo \"\\${EXTERNAL_NODE_IPS[*]}\")\nfi\nEXTERNAL_NODE_IPS_PARAM=\\${EXTERNAL_NODE_IPS_PARAM}\n\
          \n./cilium-cli status --wait\n./cilium-cli connectivity test --datapath\
          \ --collect-sysdump-on-failure \\\n  --external-from-cidrs=\"\\${EXTERNAL_NODE_IPS_PARAM}\"\
          \ \\\n  --sysdump-output-filename \"cilium-sysdump-${{ matrix.name }}-<ts>\"\
          \n./cilium-cli connectivity test --collect-sysdump-on-failure \\\n  --external-from-cidrs=\"\
          \\${EXTERNAL_NODE_IPS_PARAM}\" \\\n  --sysdump-output-filename \"cilium-sysdump-${{\
          \ matrix.name }}-<ts>\"\nkind delete cluster\n"
    - name: Run encryption tests
      if: ${{ matrix.encryption != 'disabled' }}
      uses: cilium/little-vm-helper@0b7d7157dae56a44dc531c852e7756dc671071af
      with:
        provision: 'false'
        cmd: "cd /host/\n./contrib/scripts/kind.sh \"\" 3 \"\" \"\" \"${{ matrix.kube-proxy\
          \ }}\" \"dual\"\n./cilium-cli install ${{ steps.vars.outputs.cilium_install_defaults\
          \ }} \\\n  --encryption=${{ matrix.encryption }}\n\n./cilium-cli status\
          \ --wait\n./cilium-cli connectivity test --datapath --collect-sysdump-on-failure\
          \ \\\n  --sysdump-output-filename \"cilium-sysdump-${{ matrix.name }}-<ts>\"\
          \n./cilium-cli connectivity test --collect-sysdump-on-failure \\\n  --sysdump-output-filename\
          \ \"cilium-sysdump-${{ matrix.name }}-<ts>\"\n"
    - name: Fetch artifacts
      if: ${{ !success() }}
      uses: cilium/little-vm-helper@0b7d7157dae56a44dc531c852e7756dc671071af
      with:
        provision: 'false'
        cmd: 'cd /host

          kubectl get pods --all-namespaces -o wide

          ./cilium-cli status

          mkdir -p cilium-sysdumps

          ./cilium-cli sysdump --output-filename cilium-sysdump-${{ matrix.name }}-final

          '
    - name: Upload artifacts
      if: ${{ !success() }}
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: cilium-sysdumps
        path: cilium-sysdump-*.zip
        retention-days: 5
  report-success:
    runs-on: ubuntu-latest
    needs:
    - setup-report
    - setup-and-test
    name: Set commit status to success
    if: ${{ success() }}
    steps:
    - uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ needs.setup-report.outputs.sha }}
        context: ${{ github.workflow }}
        description: E2E conformance tests successful
        state: success
        target_url: ${{ env.check_url }}
  report-failure:
    runs-on: ubuntu-latest
    needs:
    - setup-report
    - setup-and-test
    name: Set commit status to failure
    if: ${{ failure() }}
    steps:
    - uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ needs.setup-report.outputs.sha }}
        context: ${{ github.workflow }}
        description: Datapath tests failed
        state: failure
        target_url: ${{ env.check_url }}
  report-cancelled:
    runs-on: ubuntu-latest
    needs:
    - setup-report
    - setup-and-test
    name: Set commit status to cancelled
    if: ${{ cancelled() }}
    steps:
    - uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ needs.setup-report.outputs.sha }}
        context: ${{ github.workflow }}
        description: Datapath tests cancelled
        state: error
        target_url: ${{ env.check_url }}
