name: Documentation Updates
'on':
  pull_request: {}
  push:
    branches:
    - main
    - ft/main/**
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after
    }}
  cancel-in-progress: true
jobs:
  check_changes:
    name: Deduce required tests from code changes
    runs-on: ubuntu-latest
    outputs:
      docs-tree: ${{ steps.docs-tree.outputs.src }}
    steps:
    - name: Checkout code
      if: ${{ !github.event.pull_request }}
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      with:
        persist-credentials: false
    - name: Check code changes
      uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
      id: docs-tree
      with:
        base: ${{ github.ref }}
        filters: "src:\n  - .github/workflows/documentation.yaml\n  - 'Documentation/**'\n\
          \  - 'bugtool/cmd/**'\n  - 'cilium/cmd/**'\n  - 'cilium-health/cmd/**'\n\
          \  - 'daemon/cmd/**'\n  - 'hubble-relay/cmd/**'\n  - 'install/kubernetes/**'\n\
          \  - 'operator/cmd/**'\n"
  build-html:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.docs-tree == 'true' }}
    name: Validate & Build HTML
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      with:
        persist-credentials: false
    - name: Run pre-requisites for validation
      run: 'make -C Documentation copy-api # necessary for check-build.sh

        '
    - uses: docker://cilium/docs-builder:2023-03-01@sha256:36b233afd73482c2bc7ed43f7a1537f09962015c34679b86c4ca1fa618d67b95
      with:
        entrypoint: ./Documentation/check-build.sh
        args: html
