name: Chart CI Push
'on':
  workflow_run:
    workflows:
    - Image CI Build
    types:
    - completed
  workflow_dispatch:
    inputs:
      checkout_ref:
        description: Git ref to build. This needs to be a full commit SHA.
        required: true
permissions:
  contents: read
  pull-requests: read
  statuses: write
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after
    }}
  cancel-in-progress: true
env:
  check_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id
    }}
jobs:
  push-charts:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name
      == 'workflow_dispatch' || github.event_name == 'push' }}
    steps:
    - name: Checkout GitHub main
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      with:
        ref: ${{ github.event.repository.default_branch }}
        persist-credentials: false
    - name: Set Environment Variables
      uses: ./.github/actions/set-env-variables
    - name: Get triggering event ref
      id: get-ref
      run: "if [[ \"${{ github.event_name }}\" == \"workflow_dispatch\"  ]]; then\n\
        \  echo ref=\"${{ inputs.checkout_ref }}\" >> $GITHUB_OUTPUT\n  echo sha=\"\
        ${{ inputs.checkout_ref }}\" >> $GITHUB_OUTPUT\nelif [[ \"${{ github.event_name\
        \ }}\" == \"workflow_run\" ]]; then\n  if [[ \"${{ github.event.workflow_run.head_repository.fork\
        \ }}\" == \"true\"  ]]; then\n    # use the SHA on forks since the head_branch\
        \ won't exist in the upstream repository\n    echo ref=\"${{ github.event.workflow_run.head_sha\
        \ }}\" >> $GITHUB_OUTPUT\n  else\n    echo ref=\"${{ github.event.workflow_run.head_branch\
        \ }}\" >> $GITHUB_OUTPUT\n  fi\n  echo sha=\"${{ github.event.workflow_run.head_sha\
        \ }}\" >> $GITHUB_OUTPUT\nelif [[ \"${{ github.event_name }}\" == \"push\"\
        \ ]]; then\n  echo ref=\"${{ github.ref }}\" >> $GITHUB_OUTPUT\n  echo sha=\"\
        ${{ github.sha }}\" >> $GITHUB_OUTPUT\nelse\n  echo \"Invalid event type\"\
        \n  exit 1\nfi\n"
    - name: Set commit status to pending
      uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.get-ref.outputs.sha }}
        context: ${{ github.workflow }}
        description: Helm push in progress
        state: pending
        target_url: ${{ env.check_url }}
    - name: Checkout Source Code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      with:
        persist-credentials: false
        ref: ${{ steps.get-ref.outputs.ref }}
        fetch-depth: 0
    - id: get-version
      run: 'echo "chart_version=$(./contrib/scripts/print-chart-version.sh)" | tee
        -a $GITHUB_OUTPUT

        '
    - name: Push charts
      uses: cilium/reusable-workflows/.github/actions/push-helm-chart@v0.1.0
      with:
        name: cilium
        path: install/kubernetes/cilium
        version: ${{ steps.get-version.outputs.chart_version }}
        values_file_changes: "{\n\n  \"image.repository\": \"quay.io/${{ env.QUAY_ORGANIZATION_DEV\
          \ }}/cilium-ci\",\n  \"image.tag\": \"${{ steps.get-ref.outputs.sha }}\"\
          ,\n  \"preflight.image.repository\": \"quay.io/${{ env.QUAY_ORGANIZATION_DEV\
          \ }}/cilium-ci\",\n  \"preflight.image.tag\": \"${{ steps.get-ref.outputs.sha\
          \ }}\",\n  \"operator.image.repository\": \"quay.io/${{ env.QUAY_ORGANIZATION_DEV\
          \ }}/operator\",\n  \"operator.image.suffix\": \"-ci\",\n  \"operator.image.tag\"\
          : \"${{ steps.get-ref.outputs.sha }}\",\n  \"hubble.relay.image.repository\"\
          : \"quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/hubble-relay-ci\",\n  \"hubble.relay.image.tag\"\
          : \"${{ steps.get-ref.outputs.sha }}\",\n  \"clustermesh.apiserver.image.repository\"\
          : \"quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/clustermesh-apiserver-ci\"\
          ,\n  \"clustermesh.apiserver.image.tag\": \"${{ steps.get-ref.outputs.sha\
          \ }}\"\n}\n"
        registry: quay.io
        registry_namespace: ${{ env.QUAY_CHARTS_ORGANIZATION_DEV }}
        registry_username: ${{ secrets.QUAY_CHARTS_DEV_USERNAME }}
        registry_password: ${{ secrets.QUAY_CHARTS_DEV_PASSWORD }}
    - name: Print helm command
      run: 'echo "Example commands:"

        echo helm template -n kube-system oci://quay.io/${{ env.QUAY_CHARTS_ORGANIZATION_DEV
        }}/cilium --version ${{ steps.get-version.outputs.chart_version }}

        echo helm install cilium -n kube-system  oci://quay.io/${{ env.QUAY_CHARTS_ORGANIZATION_DEV
        }}/cilium --version ${{ steps.get-version.outputs.chart_version }}

        '
    - name: Set commit status to success
      if: ${{ success() }}
      uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.get-ref.outputs.sha }}
        context: ${{ github.workflow }}
        description: Helm push successful
        state: success
        target_url: ${{ env.check_url }}
    - name: Set commit status to failure
      if: ${{ failure() }}
      uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.get-ref.outputs.sha }}
        context: ${{ github.workflow }}
        description: Helm push failed
        state: failure
        target_url: ${{ env.check_url }}
    - name: Set commit status to cancelled
      if: ${{ cancelled() }}
      uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.get-ref.outputs.sha }}
        context: ${{ github.workflow }}
        description: Helm push cancelled
        state: error
        target_url: ${{ env.check_url }}
